// data.ts

export const sample_juices = [
  {
    id: '1',
    name: 'Orange Juice',
    price: 5,
    prepareTime: '10-15',
    favorite: true,
    origins: ['USA', 'Spain'],
    stars: 4.5,
    imageUrl: 'assets/images/orange-juice.jpeg',
    tags: ['Citrus', 'Fresh', 'Breakfast'],
  },
  {
    id: '2',
    name: 'Apple Juice',
    price: 4,
    prepareTime: '10-15',
    favorite: true,
    origins: ['USA', 'China'],
    stars: 4.7,
    imageUrl: 'assets/images/apple-juice.jpg',
    tags: ['Sweet', 'Fresh', 'Breakfast'],
  },
  {
    id: '3',
    name: 'Carrot Juice',
    price: 6,
    prepareTime: '15-20',
    favorite: false,
    origins: ['USA', 'Europe'],
    stars: 4.2,
    imageUrl: 'assets/images/carrot-juice.jpg',
    tags: ['Healthy', 'Detox', 'Vegetable'],
  },
  {
    id: '4',
    name: 'Pineapple Juice',
    price: 7,
    prepareTime: '10-15',
    favorite: true,
    origins: ['Philippines', 'Thailand'],
    stars: 4.8,
    imageUrl: 'assets/images/pineapple-juice.jpeg',
    tags: ['Tropical', 'Sweet', 'Fresh'],
  },
  {
    id: '5',
    name: 'Grape Juice',
    price: 6,
    prepareTime: '15-20',
    favorite: false,
    origins: ['Italy', 'France'],
    stars: 4.3,
    imageUrl: 'assets/images/grape-juice.jpg',
    tags: ['Sweet', 'Fresh', 'Fruit'],
  },
  {
    id: '6',
    name: 'Beet Juice',
    price: 8,
    prepareTime: '20-25',
    favorite: false,
    origins: ['USA', 'Europe'],
    stars: 4.1,
    imageUrl: 'assets/images/beet-juice.jpg',
    tags: ['Healthy', 'Detox', 'Vegetable'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'Citrus', count: 1 },
  { name: 'Sweet', count: 2 },
  { name: 'Healthy', count: 2 },
  { name: 'Fresh', count: 4 },
  { name: 'Tropical', count: 1 },
  { name: 'Detox', count: 2 },
  { name: 'Vegetable', count: 2 },
  { name: 'Fruit', count: 1 },
  { name: 'Breakfast', count: 2 },
];

export const sample_users = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '1234',
    adress: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '1234',
    adress: 'Shanghai',
    isAdmin: false,
  },
  {
    name: 'Milica Vujanovic',
    email: 'milica@gmail.com',
    password: 'milica123',
    adress: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Sanja Vujanovic',
    email: 'sanja@gmail.com',
    password: 'sanja123',
    adress: 'Toronto On',
    isAdmin: false,
  }
];
